# General Jekyll Config
url: http://philipjagielski.com
lsi: false
exclude: [README.md, .gitignore, exportAWSCreds]
timezone: America/Chicago

# Theme customization
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'

  # Profile links on the left sidebar
  social:
    github: positron
    linkedin: philipjagielski
    gplus: 110552447039675960964

  name: Philip Jagielski
  email: philipjagielski@gmail.com

  google_analytics_key: UA-21100317-2

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
